site:
  title: Blog Preview (Standard UI)
  start_page: blog::index.adoc

content:
  sources:
    - url: /Users/timsparg/source/sandbox/antora-ui-default
      start_path: preview-antora-cli

ui:
  bundle:
    url: https://github.com/asciidoctor/asciidoctor-docs-ui/releases/download/prod-latest/ui-bundle.zip
    snapshot: true

output:
  dir: build/antora-cli

runtime:
  fetch: true
